-- Accounts Table Adaption

ALTER TABLE `accounts`
ADD COLUMN `key` VARCHAR(64) NOT NULL DEFAULT '';

ALTER TABLE `accounts` ADD COLUMN `country` VARCHAR(3) NOT NULL DEFAULT '';

ALTER TABLE accounts ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE accounts ADD COLUMN secret_status BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN secret CHAR(16) NULL;

ALTER TABLE accounts ADD COLUMN web_lastlogin INT UNSIGNED DEFAULT 0;

ALTER TABLE accounts ADD COLUMN rlname VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE accounts ADD COLUMN phone VARCHAR(15) NULL;

