import { encryptPassword } from '@/utils/functions/criptoPassword';
import { randomKey } from '@/utils/functions/randomKey';
import { PrismaClient } from '@prisma/client';
import dayjs from 'dayjs';

const prisma = new PrismaClient();

const password = encryptPassword('Z4me5cwh*');
const key = randomKey();
export const adminAccount = {
	id: 1,
	name: 'god',
	password: password,
	email: 'admin@god.com',
	created: new Date(0),
	rlname: '',
	location: '',
	country: '',
	web_lastlogin: new Date(0),
	web_flags: 0,
	email_hash: '',
	email_new: '',
	email_new_time: new Date(0),
	email_code: '',
	email_next: new Date(0),
	email_verified: 0,
	phone: null,
	key: '',
	premdays: 0,
	premdays_purchased: 0,
	lastday: new Date(0),
	type: 6,
	coins: 0,
	coins_transferable: 0,
	tournament_coins: 0,
	creation: new Date(1729568360 * 1000),
	recruiter: 0,
	vote: 0,
};

export const sampleRook = {
	id: 1,
	name: 'Rook Sample',
	group_id: 1,
	account_id: 1,
	level: 2,
	vocation: 0,
	health: 155,
	healthmax: 155,
	experience: 100,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 2,
	mana: 60,
	manamax: 60,
	manaspent: 5936,
	soul: 0,
	town_id: 1,
	posx: 32069,
	posy: 31901,
	posz: 6,
	conditions: '',
	cap: 410,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	save: 1,
	skull: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	quickloot_fallback: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	isreward: 0,
	istutorial: 0,
	ismain: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	randomize_mount: 0,
	boss_points: 0,
	created: 100,
	hidden: 0,
	comment: '',
};

export const sampleSorcerer = {
	id: 2,
	name: 'Sorcerer Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 1,
	health: 185,
	healthmax: 185,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 8,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: '',
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	save: 1,
	skull: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	quickloot_fallback: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	isreward: 0,
	istutorial: 0,
	ismain: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	randomize_mount: 0,
	boss_points: 0,
	created: 100,
	hidden: 0,
	comment: '',
};

export const sampleBoostedCreature = [
	{
		boostname: 'Mushroom Sniffer',
		date: '870',
		raceid: '60',
		looktype: 0,
		lookfeet: 0,
		looklegs: 0,
		lookhead: 0,
		lookbody: 0,
		lookaddons: 0,
		lookmount: 0,
	},
];

export const sampleBoostedBoss = [
	{
		boostname: 'Srezz Yellow Eyes',
		date: '4',
		raceid: '1983',
		looktypeEx: 0,
		looktype: 220,
		lookfeet: 0,
		looklegs: 0,
		lookhead: 0,
		lookbody: 0,
		lookaddons: 0,
		lookmount: 0,
	},
];

async function seed() {
	// await prisma.accounts.createMany({
	// 	data: [{ id: 1, name: 'god', email: 'jhondoe@example.com', key, email_verified: true, password, type: 6, create_date: dayjs().unix() }],
	// 	skipDuplicates: true,
	// });

	// await prisma.players.createMany({ data: samplePlayer, skipDuplicates: true });
	// await prisma.towns.createMany({ data: positions, skipDuplicates: true });
	await prisma.boosted_boss.createMany({
		data: sampleBoostedBoss,
		skipDuplicates: true,
	});
	await prisma.boosted_creature.createMany({
		data: sampleBoostedCreature,
		skipDuplicates: true,
	});
}

seed()
	.catch((error) => {
		console.log(error);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
