import { PrismaClient } from '@prisma/client'
import { encryptPassword } from '../src/utils/functions/criptoPassword';
//import { randomKey } from '@/utils/functions/randomKey';
import dayjs from 'dayjs';


//import config from '@/lib/config';

//const key = randomKey();

const prisma = new PrismaClient()

const password = encryptPassword('Z4me5cwh*$%');
export const sampleAccount = {
	id: 1,
	name: 'godwwytk2mu',
	password: password,
	email: 'admin@godwwytkmu.com',
	created: dayjs().unix(),
	rlname: '',
	location: '',
	country: '',
	web_lastlogin: 0,
	web_flags: 0,
	email_hash: '',
	email_new: '',
	email_new_time: 0,
	email_code: '',
	email_next: 0,
	email_verified: true,
	phone: null,
	key: '',
	premdays: 0,
	premdays_purchased: 0,
	lastday: 0,
	type: 6,
	coins: 0,
	coins_transferable: 0,
	tournament_coins: 0,
	creation: dayjs().unix(),
	recruiter: 0,
	vote: 0,
	secret: '',
	secret_status: false,
	gamesecret: '',
	authToken: '',
};

// const sampleCommon = {
// 	group_id: 1,
// 	account_id: 1,
// 	healthmax: 155,
// 	experience: BigInt(100),
// 	lookbody: 113,
// 	lookfeet: 115,
// 	lookhead: 95,
// 	looklegs: 39,
// 	looktype: 129,
// 	lookaddons: 0,
// 	mana: 60,
// 	manamax: 60,
// 	manaspent: BigInt(5936),
// 	soul: 0,
// 	conditions: Buffer.alloc(1024),
// 	cap: 410,
// 	sex: 1,
// 	pronoun: 0,
// 	skulltime: 0,
// 	lastlogout: 0,
// 	blessings: 0,
// 	blessings1: 0,
// 	blessings2: 0,
// 	blessings3: 0,
// 	blessings4: 0,
// 	blessings5: 0,
// 	blessings6: 0,
// 	blessings7: 0,
// 	blessings8: 0,
// 	onlinetime: 43200,
// 	deletion: -1,
// 	balance: 2520,
// 	offlinetraining_time: 10,
// 	offlinetraining_skill: 0,
// 	stamina: 43200,
// 	skill_fist: 10,
// 	skill_fist_tries: 0,
// 	skill_club: 10,
// 	skill_club_tries: 0,
// 	skill_sword: 10,
// 	skill_sword_tries: 0,
// 	skill_axe: 10,
// 	skill_axe_tries: 0,
// 	skill_dist: 10,
// 	skill_dist_tries: 0,
// 	skill_shielding: 10,
// 	skill_shielding_tries: 0,
// 	skill_fishing: 0,
// 	skill_fishing_tries: 0,
// 	skill_critical_hit_chance: 0,
// 	skill_critical_hit_chance_tries: 0,
// 	skill_critical_hit_damage: 0,
// 	skill_critical_hit_damage_tries: 0,
// 	skill_life_leech_chance: 0,
// 	skill_life_leech_chance_tries: 0,
// 	skill_life_leech_amount: 0,
// 	skill_life_leech_amount_tries: 0,
// 	skill_mana_leech_chance: 0,
// 	skill_mana_leech_chance_tries: 0,
// 	skill_mana_leech_amount: 0,
// 	skill_mana_leech_amount_tries: 0,
// 	skill_criticalhit_chance: 0,
// 	skill_criticalhit_damage: 0,
// 	skill_lifeleech_chance: 0,
// 	skill_lifeleech_amount: 0,
// 	skill_manaleech_chance: 0,
// 	skill_manaleech_amount: 0,
// 	manashield: 0,
// 	max_manashield: 0,
// 	xpboost_stamina: 0,
// 	xpboost_value: 0,
// 	marriage_status: 0,
// 	marriage_spouse: 0,
// 	bonus_rerolls: 0,
// 	prey_wildcard: 0,
// 	task_points: 0,
// 	lookmountbody: 0,
// 	lookmountfeet: 0,
// 	lookmounthead: 0,
// 	lookmountlegs: 0,
// 	lookfamiliarstype: 0,
// 	forge_dusts: 0,
// 	forge_dust_level: 0,
// 	boss_points: 0,
// 	created: 100,
// 	comment: '',
// };

export const sampleRook = {
	id: 1,
	name: 'Rook Sample',
	group_id: 1,
	account_id: 1,
	level: 2,
	vocation: 0,
	health: 155,
	healthmax: 155,
	experience: BigInt(100),
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 2,
	mana: 60,
	manamax: 60,
	manaspent: BigInt(5936),
	soul: 0,
	town_id: 1,
	posx: 32069,
	posy: 31901,
	posz: 6,
	conditions: Buffer.alloc(1024),
	cap: 410,
	sex: 1,
	pronoun: 0,
	lastlogin: BigInt(0),
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const sampleSorcerer = {
	id: 2,
	name: 'Sorcerer Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 1,
	health: 185,
	healthmax: 185,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 8,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Buffer.alloc(1024),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const druidSample = {
	id: 3,
	name: 'Druid Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 2,
	health: 185,
	healthmax: 185,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 130,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 9,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Buffer.alloc(1024),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const paladinSample = {
	id: 4,
	name: 'Paladin Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 3,
	health: 190,
	healthmax: 190,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 10,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Buffer.alloc(1024),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const knighSample = {
	id: 5,
	name: 'Knight Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 4,
	health: 250,
	healthmax: 250,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 131,
	lookaddons: 0,
	maglevel: 0,
	mana: 60,
	manamax: 60,
	manaspent: 0,
	soul: 0,
	town_id: 11,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Buffer.alloc(1024),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const sampleBoostedCreature = {
	boostname: 'Mushroom Sniffer',
	date: '870',
	raceid: '60',
	looktype: 0,
	lookfeet: 0,
	looklegs: 0,
	lookhead: 0,
	lookbody: 0,
	lookaddons: 0,
	lookmount: 0,
};

export const sampleBoostedBoss = {
	boostname: 'Srezz Yellow Eyes',
	date: '4',
	raceid: '1983',
	looktypeEx: 0,
	looktype: 220,
	lookfeet: 0,
	looklegs: 0,
	lookhead: 0,
	lookbody: 0,
	lookaddons: 0,
	lookmount: 0,
};




async function seed() {
	// await prisma.accounts.createMany({
	// 	data: [{ id: 1, name: 'god', email: 'jhondoe@example.com', key, email_verified: true, password, type: 6, create_date: dayjs().unix() }],
	// 	skipDuplicates: true,
	// });

	// await prisma.players.createMany({ data: samplePlayer, skipDuplicates: true });
	// await prisma.towns.createMany({ data: positions, skipDuplicates: true });

	await prisma.accounts.createMany({
		data: sampleAccount,
		skipDuplicates: true,
	});

	await prisma.players.createMany({
		data: [sampleRook, sampleSorcerer, druidSample, paladinSample, knighSample],
		skipDuplicates: true,
	});

	await prisma.boosted_boss.createMany({
		data: sampleBoostedBoss,
		skipDuplicates: true,
	});

	await prisma.boosted_creature.createMany({
		data: sampleBoostedCreature,
		skipDuplicates: true,
	});
}

seed()
	.finally(async () => {
		await prisma.$disconnect();
	})
	.catch((error) => {
		console.log(error);
		process.exit(1);
	});
