import { BATTLEPASS_PERIOD_TYPE_TASKS, BATTLEPASS_RANK_ACCESS, BATTLEPASS_TYPE_TASKS, PrismaClient, type players, type Prisma, type products_categories, } from '@prisma/client'
import { encryptPassword } from '../src/utils/functions/criptoPassword';
//import { randomKey } from '@/utils/functions/randomKey';
import dayjs from 'dayjs';
import type { Args, GetPayloadResult } from '@prisma/client/runtime/library';
import { countries} from "../src/app/account-manager/(manager)/components/data/countries";


//import config from '@/lib/config';

//const key = randomKey();

const prisma = new PrismaClient()

const password = encryptPassword('Z4me5cwh*$%');
export const sampleAccount = {
	id: 1,
	name: 'godwwytk2mu',
	password: password,
	email: 'admin@godwwytkmu.com',
	created: dayjs().unix(),
	rlname: '',
	location: '',
	country: '',
	web_lastlogin: 0,
	web_flags: 0,
	email_hash: '',
	email_new: '',
	email_new_time: 0,
	email_code: '',
	email_next: 0,
	email_verified: true,
	phone: null,
	key: '',
	premdays: 0,
	premdays_purchased: 0,
	lastday: 0,
	type: 6,
	coins: 0,
	coins_transferable: 0,
	tournament_coins: 0,
	creation: dayjs().unix(),
	recruiter: 0,
	vote: 0,
	secret: '',
	secret_status: false,
	gamesecret: '',
	authToken: '',
};
export const godAccount = {
	id: 2,
	name: 'wwytk2mu',
	password: password,
	email: 'heathcliff@god.com',
	created: dayjs().unix(),
	rlname: '',
	location: '',
	country: '',
	web_lastlogin: 0,
	web_flags: 0,
	email_hash: '',
	email_new: '',
	email_new_time: 0,
	email_code: '',
	email_next: 0,
	email_verified: true,
	phone: null,
	key: '',
	premdays: 0,
	premdays_purchased: 0,
	lastday: 0,
	type: 6,
	coins: 0,
	coins_transferable: 0,
	tournament_coins: 0,
	creation: dayjs().unix(),
	recruiter: 0,
	vote: 0,
	secret: '',
	secret_status: false,
	gamesecret: '',
	authToken: '',
};

// const sampleCommon = {
// 	group_id: 1,
// 	account_id: 1,
// 	healthmax: 155,
// 	experience: BigInt(100),
// 	lookbody: 113,
// 	lookfeet: 115,
// 	lookhead: 95,
// 	looklegs: 39,
// 	looktype: 129,
// 	lookaddons: 0,
// 	mana: 60,
// 	manamax: 60,
// 	manaspent: BigInt(5936),
// 	soul: 0,
// 	conditions: Uint8Array.from({ length: 1024 }),
// 	cap: 410,
// 	sex: 1,
// 	pronoun: 0,
// 	skulltime: 0,
// 	lastlogout: 0,
// 	blessings: 0,
// 	blessings1: 0,
// 	blessings2: 0,
// 	blessings3: 0,
// 	blessings4: 0,
// 	blessings5: 0,
// 	blessings6: 0,
// 	blessings7: 0,
// 	blessings8: 0,
// 	onlinetime: 43200,
// 	deletion: -1,
// 	balance: 2520,
// 	offlinetraining_time: 10,
// 	offlinetraining_skill: 0,
// 	stamina: 43200,
// 	skill_fist: 10,
// 	skill_fist_tries: 0,
// 	skill_club: 10,
// 	skill_club_tries: 0,
// 	skill_sword: 10,
// 	skill_sword_tries: 0,
// 	skill_axe: 10,
// 	skill_axe_tries: 0,
// 	skill_dist: 10,
// 	skill_dist_tries: 0,
// 	skill_shielding: 10,
// 	skill_shielding_tries: 0,
// 	skill_fishing: 0,
// 	skill_fishing_tries: 0,
// 	skill_critical_hit_chance: 0,
// 	skill_critical_hit_chance_tries: 0,
// 	skill_critical_hit_damage: 0,
// 	skill_critical_hit_damage_tries: 0,
// 	skill_life_leech_chance: 0,
// 	skill_life_leech_chance_tries: 0,
// 	skill_life_leech_amount: 0,
// 	skill_life_leech_amount_tries: 0,
// 	skill_mana_leech_chance: 0,
// 	skill_mana_leech_chance_tries: 0,
// 	skill_mana_leech_amount: 0,
// 	skill_mana_leech_amount_tries: 0,
// 	skill_criticalhit_chance: 0,
// 	skill_criticalhit_damage: 0,
// 	skill_lifeleech_chance: 0,
// 	skill_lifeleech_amount: 0,
// 	skill_manaleech_chance: 0,
// 	skill_manaleech_amount: 0,
// 	manashield: 0,
// 	max_manashield: 0,
// 	xpboost_stamina: 0,
// 	xpboost_value: 0,
// 	marriage_status: 0,
// 	marriage_spouse: 0,
// 	bonus_rerolls: 0,
// 	prey_wildcard: 0,
// 	task_points: 0,
// 	lookmountbody: 0,
// 	lookmountfeet: 0,
// 	lookmounthead: 0,
// 	lookmountlegs: 0,
// 	lookfamiliarstype: 0,
// 	forge_dusts: 0,
// 	forge_dust_level: 0,
// 	boss_points: 0,
// 	created: 100,
// 	comment: '',
// };

export const sampleRook = {
	id: 1,
	name: 'Rook Sample',
	group_id: 1,
	account_id: 1,
	level: 2,
	vocation: 0,
	health: 155,
	healthmax: 155,
	experience: BigInt(100),
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 2,
	mana: 60,
	manamax: 60,
	manaspent: BigInt(5936),
	soul: 0,
	town_id: 1,
	posx: 32069,
	posy: 31901,
	posz: 6,
	conditions: Uint8Array.from({ length: 1024 }),
	cap: 410,
	sex: 1,
	pronoun: 0,
	lastlogin: BigInt(0),
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const sampleAdmin = {
	...sampleRook,
	group_id: 6,
	account_id: 2,
	town_id: 8,
	looktype: 302,
	lookfeet: 0,
	looklegs: 0,
	lookhead: 0,
	lookbody: 0,
	lookaddons: 0,
	health: 1,
	healthmax: 1,
	level: 1,
	mana: 1,
	manamax: 1,
}

export const sampleSorcerer = {
	id: 2,
	name: 'Sorcerer Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 1,
	health: 185,
	healthmax: 185,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 8,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Uint8Array.from({ length: 1024 }),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const druidSample = {
	id: 3,
	name: 'Druid Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 2,
	health: 185,
	healthmax: 185,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 130,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 9,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Uint8Array.from({ length: 1024 }),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const paladinSample = {
	id: 4,
	name: 'Paladin Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 3,
	health: 190,
	healthmax: 190,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 129,
	lookaddons: 0,
	maglevel: 0,
	mana: 90,
	manamax: 90,
	manaspent: 0,
	soul: 0,
	town_id: 10,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Uint8Array.from({ length: 1024 }),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const knighSample = {
	id: 5,
	name: 'Knight Sample',
	group_id: 1,
	account_id: 1,
	level: 8,
	vocation: 4,
	health: 250,
	healthmax: 250,
	experience: 4200,
	lookbody: 113,
	lookfeet: 115,
	lookhead: 95,
	looklegs: 39,
	looktype: 131,
	lookaddons: 0,
	maglevel: 0,
	mana: 60,
	manamax: 60,
	manaspent: 0,
	soul: 0,
	town_id: 11,
	posx: 32369,
	posy: 32241,
	posz: 7,
	conditions: Uint8Array.from({ length: 1024 }),
	cap: 470,
	sex: 1,
	pronoun: 0,
	lastlogin: 0,
	lastip: 0,
	skulltime: 0,
	lastlogout: 0,
	blessings: 0,
	blessings1: 0,
	blessings2: 0,
	blessings3: 0,
	blessings4: 0,
	blessings5: 0,
	blessings6: 0,
	blessings7: 0,
	blessings8: 0,
	onlinetime: 43200,
	deletion: -1,
	balance: 2520,
	offlinetraining_time: 10,
	offlinetraining_skill: 0,
	stamina: 43200,
	skill_fist: 10,
	skill_fist_tries: 0,
	skill_club: 10,
	skill_club_tries: 0,
	skill_sword: 10,
	skill_sword_tries: 0,
	skill_axe: 10,
	skill_axe_tries: 0,
	skill_dist: 10,
	skill_dist_tries: 0,
	skill_shielding: 10,
	skill_shielding_tries: 0,
	skill_fishing: 0,
	skill_fishing_tries: 0,
	skill_critical_hit_chance: 0,
	skill_critical_hit_chance_tries: 0,
	skill_critical_hit_damage: 0,
	skill_critical_hit_damage_tries: 0,
	skill_life_leech_chance: 0,
	skill_life_leech_chance_tries: 0,
	skill_life_leech_amount: 0,
	skill_life_leech_amount_tries: 0,
	skill_mana_leech_chance: 0,
	skill_mana_leech_chance_tries: 0,
	skill_mana_leech_amount: 0,
	skill_mana_leech_amount_tries: 0,
	skill_criticalhit_chance: 0,
	skill_criticalhit_damage: 0,
	skill_lifeleech_chance: 0,
	skill_lifeleech_amount: 0,
	skill_manaleech_chance: 0,
	skill_manaleech_amount: 0,
	manashield: 0,
	max_manashield: 0,
	xpboost_stamina: 0,
	xpboost_value: 0,
	marriage_status: 0,
	marriage_spouse: 0,
	bonus_rerolls: 0,
	prey_wildcard: 0,
	task_points: 0,
	lookmountbody: 0,
	lookmountfeet: 0,
	lookmounthead: 0,
	lookmountlegs: 0,
	lookfamiliarstype: 0,
	forge_dusts: 0,
	forge_dust_level: 0,
	boss_points: 0,
	created: 100,
	comment: '',
};

export const sampleBoostedCreature = {
	boostname: 'Mushroom Sniffer',
	date: '4',
	raceid: '60',
	looktype: 870,
	lookfeet: 0,
	looklegs: 0,
	lookhead: 0,
	lookbody: 0,
	lookaddons: 0,
	lookmount: 0,
};

export const sampleBoostedBoss = {
	boostname: 'Srezz Yellow Eyes',
	date: '4',
	raceid: '1983',
	looktypeEx: 0,
	looktype: 220,
	lookfeet: 0,
	looklegs: 0,
	lookhead: 0,
	lookbody: 0,
	lookaddons: 0,
	lookmount: 0,
};



export const nocteraCoinProductCategory: Args<typeof prisma.products_categories, "createMany">['data'] = [
	{
		id: 1,
		name: 'Noctera Coins',
img_url:'serviceid_193_transferable.gif'
	}
]

// TODO: add noctera coin products
export const nocteraCoinProducts: Args<typeof prisma.products, "createMany">['data'] = [
	{
		id: 1,
		category_id: 1,
		title: '100 Noctera Coins',
		quantity: 100,
		price: "4.99",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_193_transferable.gif'
	},
	{ // Save 12%
		id: 2,
		category_id: 1,
		title: '250 Noctera Coins',
		quantity: 250,
		price: "10.99",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_194_transferable.gif'
	},
	{ // Save 15%
		id: 3,
		category_id: 1,
		title: '500 Noctera Coins',
		quantity: 500,
		price: "21.25",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_195_transferable.gif'
	},
	{ // Save 20%
		id: 4,
		category_id: 1,
		title: '1200 Noctera Coins',
		quantity: 1200,
		price: "47.99",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_196_transferable.gif'
	},
	{ // Save 20%
		id: 5,
		category_id: 1,
		title: '2500 Noctera Coins',
		quantity: 2500,
		price: "99.99",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_197_transferable.gif'
	},
	{ // Save 35%
		id: 6,
		category_id: 1,
		title: '6500 Noctera Coins',
		quantity: 6500,
		price: "212.99",
		currency: 'USD',
		content: '',
		img_url: 'serviceid_198_transferable.gif'
	}
]

// // products
// export const sampleProductCategories: products_categories = {
// 	img_url: 'd2bc1428-a3c1-492e-8cf1-84679d4ecd9a-Premium_Time_360.png'
// 	name: 'Vip',
// 	desc: 'Vip',
// }
// // categories


export const dailyMonsterKillTemplateTasksFree: Args<typeof prisma.battlepass_task_templates, "createMany">['data'] = [
	{
		id: 1,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 2,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 3,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 4,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 5,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 6,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 7,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 8,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 9,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	},
	{
		id: 10,
		name: '',
		description: '',
		task_img: '',
		period_type: BATTLEPASS_PERIOD_TYPE_TASKS.DAILY,
		task_type: BATTLEPASS_TYPE_TASKS.MONSTER_KILL,
		task_value: '',
		task_amount: 1,
		weight: 1,
		enabled: true,
		notes: '',
		min_rank_access: BATTLEPASS_RANK_ACCESS.FREE,
	}
]

async function seed() {
	// seedBoostedCreatures()
	// seedSampleAccount({withPlayers: true})
	// seedShopProducts()
	// seedExchangeRates()
}

async function seedSampleAccount({withPlayers = true}: {withPlayers?: boolean} = {withPlayers: true}) {
	await prisma.accounts.createMany({
		data: [sampleAccount],
		skipDuplicates: true,
	});
	if (withPlayers) await seedSamplePlayers()
}

async function seedSamplePlayers() {
	await prisma.players.createMany({
		data: [
			sampleRook,
			 sampleSorcerer,
			  druidSample,
			   paladinSample,
			    knighSample,
				 sampleAdmin],
		skipDuplicates: true,
	});
}

async function seedBoostedCreatures() {
	await prisma.boosted_boss.createMany({
		data: sampleBoostedBoss,
		skipDuplicates: true,
	});

	await prisma.boosted_creature.createMany({
		data: sampleBoostedCreature,
		skipDuplicates: true,
	});
}

async function seedShopProducts() {
	await prisma.products_categories.createMany({
		data: nocteraCoinProductCategory,
		skipDuplicates: true,
	});
	await prisma.products.createMany({
		data: nocteraCoinProducts,
		skipDuplicates: true,
	});
	
}

async function seedExchangeRates() {
	const exchangeRates = countries.map((c) => {
		return {
			base_currency: "usd",
			target_currency: c.code,
			rate: 1,
		}
	})
	console.log(exchangeRates);

	await prisma.exchange_rates.createMany({
		data: exchangeRates,
		skipDuplicates: true,
	});
}

seed()
	.finally(async () => {
		await prisma.$disconnect();
	})
	.catch((error) => {
		console.log(error);
		process.exit(1);
	});
